import type {Metadata} from "next";
import { Inter } from "next/font/google";
import Navber from "./components/Navber/page"
import AccessAlarmIcon from '@mui/icons-material/AccessAlarm';
import ThreeDRotation from '@mui/icons-material/ThreeDRotation';


import "./globals.css";


const inter = Inter({ subsets: ["latin"]});
export const metadata: Metadata ={
  title: "Cyborg",
  description: "Generated by create next app",
};
export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <header>
        <Navber/>
        </header>
        {children}
      </body>
    </html>
  );
}
